# Mouse Emulation
CONFIG_ZMK_POINTING=y

# Trackball
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_MOUSE=y

# Trackball Shift
CONFIG_ZMK_TRACKBALL_SHIFT_DIRECTION_ANGLE_DEG=5

# Battery
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=30
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=10
